import mongoose from "mongoose";

// Sub-schema: each passenger in the booking (up to 6 per booking)
const passengerSchema=new mongoose.Schema(
    {
        name:{
            type:String,
            required:true,
            trim:true,
        },
        age:{
            type:Number,
            required:true,
        },
        gender:{
            type:String,
            enum:["Male","Female","Other"],
            required:true,
        },
        berthPreference:{
            type:String,
            enum:["Lower","Middle","Upper","Side-Lower","Side-Upper","NoPreference"],
            default:"NoPreference",
        },
        berthAllotted:{
            //actual berth allotted after booking — filled by system
            type:String,
            default:null,
        },
        seatId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Seat",
            default:null,
        },
        idProofType:{
            type:String,
            enum:["Aadhar","PAN","Passport","None"],
            default:"None",
        },
        idProofNumber:{
            type:String,
            default:null,
        },
    },
    {_id:false}
);

const bookingSchema=new mongoose.Schema(
    {
        pnr:{
            //e.g. "PK4519372" — generated by pnrGenerator util
            type:String,
            required:true,
            unique:true,
            uppercase:true,
        },
        userId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
            required:true,
        },
        scheduleId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Schedule",
            required:true,
        },
        boardingStationId:{
            //Where passenger boards (may differ from train origin)
            type:mongoose.Schema.Types.ObjectId,
            ref:"Station",
            required:true,
        },
        destinationStationId:{
            //where passenger exits (may differ from train terminus)
            type:mongoose.Schema.Types.ObjectId,
            ref:"Station",
            required:true,
        },
        coachType:{
            type:String,
            enum:["1A","2A","3A","SL","CC","GEN"],
            required:true,
        },
        passengers:[passengerSchema],
        status:{
            type:String,
            enum:["Confirmed","Waitlisted","RAC","Cancelled","PNRCharted"],
            default:"Confirmed",
        },
        waitlistNumber:{
            //only set when status is Waitlisted
            type:Number,
            default:null,
        },
        totalFare:{
            type:Number,
            required:true,
        },
        paymentId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Payment",
            default:null,
        },
        isTatkal:{
            type:Boolean,
            default:false,
        },
        travelDate:{
            type:Date,
            required:true,
        },
        cancellationTime:{
            type:Date,
            default:null,
        },
        refundAmount:{
            type:Number,
            default:0,
        },
    },
    {timestamps:true}
);

export const Booking=mongoose.model("Booking",bookingSchema);
